"use client";
import { useOnboarding } from '@/lib/onboarding-store';
import { emptyMatchSettings, emptyTrip, matchProfile } from '@/lib/match-profile';
import type { InfraKey, MatchSettings, Priority } from '@/types/recommendations-v2';

const input='mt-1 w-full min-w-0 rounded-xl border border-[#cadbd5] bg-white p-2 text-sm';
const labels:Record<InfraKey,string>={stop:'Остановки',school:'Школы',kindergarten:'Детские сады',healthcare:'Медицина',parks:'Парки'};
const number=(v:string)=>v==='' ? null : Number(v);
function PriorityInput({label,value,onChange}:{label:string;value:Priority;onChange:(v:Priority)=>void}){
  return <label className="block text-sm">{label}<select aria-label={label} className={input} value={value ?? ''} onChange={e=>onChange(e.target.value==='' ? null : Number(e.target.value) as Priority)}><option value="">Не указано</option>{['Не важно','Немного важно','Важно','Очень важно'].map((t,i)=><option key={i} value={i}>{t}</option>)}</select></label>;
}
export function MatchPreferences(){
  const draft=useOnboarding(s=>s.draft),patch=useOnboarding(s=>s.patch);
  const settings=draft.match_v2 ?? emptyMatchSettings();
  const change=(p:Partial<MatchSettings>)=>patch({match_v2:{...settings,...p}});
  const profile=matchProfile(draft);
  return <section aria-label="Настройки Match V2" className="min-w-0 space-y-5 rounded-[22px] bg-white p-5 text-[#153c44]">
    <h2 className="text-xl font-semibold">Ваши требования к месту</h2>
    <label className="block">Сценарий жилья<select aria-label="Сценарий жилья Match" className={input} value={draft.housing_goal} onChange={e=>patch({housing_goal:e.target.value as typeof draft.housing_goal})}><option value="buy">Покупка</option><option value="rent">Аренда — полный Match недоступен</option><option value="compare">Покупка и аренда — полный Match недоступен</option></select></label>
    <p className="text-sm">Старые ответы 0–100 не преобразуются автоматически. Уточните приоритеты 0–3; «не указано» отличается от «не важно». Настройки общие для анкеты, результатов и карты.</p>
    <fieldset className="grid gap-3 sm:grid-cols-2"><legend className="mb-2 font-semibold">Инфраструктура</legend>{(Object.keys(labels) as InfraKey[]).map(k=><div key={k}><PriorityInput label={`Приоритет: ${labels[k]}`} value={settings.infrastructure[k]} onChange={v=>change({infrastructure:{...settings.infrastructure,[k]:v}})}/><label className="mt-2 block text-xs">Обязательное расстояние до {labels[k].toLowerCase()}, м<input aria-label={`Обязательное расстояние: ${labels[k]}`} className={input} type="number" min="0" value={settings.max_distance_m[k==='stop'?'stop_availability':k] ?? ''} onChange={e=>{const distances={...settings.max_distance_m};const key=k==='stop'?'stop_availability':k;const value=number(e.target.value);if(value===null)delete distances[key];else distances[key]=value;change({max_distance_m:distances});}}/></label></div>)}</fieldset>
    <p className="text-xs">Расстояния по пространственной методике OSM, не пеший маршрут. Качество и вместимость услуг не оцениваются.</p>
    <fieldset className="grid gap-3 sm:grid-cols-3"><legend className="mb-2 font-semibold">Важность областей в общем Match</legend>{(['infrastructure','mobility','affordability'] as const).map(k=><div key={k}><PriorityInput label={`Область: ${{infrastructure:'Инфраструктура',mobility:'Поездки',affordability:'Финансы'}[k]}`} value={settings.domains[k]} onChange={v=>change({domains:{...settings.domains,[k]:v}})}/><p className="mt-1 text-xs">Вес: {profile.weights[k]===null ? 'не задан' : `${(profile.weights[k]!*100).toFixed(1)}%`}</p></div>)}</fieldset>
    <div className="grid gap-3 sm:grid-cols-2"><label>Максимальный бюджет покупки, ₽<input aria-label="Максимальный бюджет Match" className={input} type="number" min="1" value={draft.purchase_budget || ''} onChange={e=>patch({purchase_budget:number(e.target.value) ?? 0})}/></label><label>Комфортная цена, ₽ — необязательно<input aria-label="Комфортная цена Match" className={input} type="number" min="1" value={settings.comfortable_price ?? ''} onChange={e=>change({comfortable_price:number(e.target.value)})}/></label></div>
    <p className="text-xs">Максимальный бюджет — обязательная проверка. Для финансового балла нужна меньшая комфортная цена; иначе исключите финансовую область из суммы. Цена «от» не гарантирует наличие квартиры.</p>
    <label className="block">Транспорт для Match<select aria-label="Транспорт Match" className={input} value={settings.mode ?? ''} onChange={e=>change({mode:e.target.value===''?null:e.target.value as MatchSettings['mode']})}><option value="">Не указан</option><option value="car">Автомобиль, без текущих пробок</option><option value="public_transport">Общественный транспорт — данные недоступны</option></select></label>
    {draft.life_points.length===0 && <p className="text-sm">Важные места добавляются на карте в анкете. Для инфраструктурного расчёта можно исключить поездки.</p>}
    {draft.life_points.length>5 && <p role="alert">В первой версии поддерживается до пяти важных мест. Уточните список в анкете.</p>}
    {draft.life_points.map(p=>{const trip=settings.trips[p.localId] ?? emptyTrip();const update=(v:Partial<typeof trip>)=>change({trips:{...settings.trips,[p.localId]:{...trip,...v}}});return <fieldset key={p.localId} className="space-y-3 rounded-xl border p-3"><legend className="px-1 font-semibold">{p.name}{p.owner_type==='partner'?' · партнёр':''}</legend><PriorityInput label={`Важность поездки: ${p.name}`} value={trip.importance} onChange={importance=>update({importance})}/>{([['visits_per_week','Поездок в неделю',0,14],['comfortable_minutes','Комфортное время, мин',0,1440],['soft_limit_minutes','Мягкий предел, мин',0.1,1440],['hard_limit_minutes','Обязательный максимум, мин',0.1,1440]] as const).map(([key,label,min,max])=><label key={key} className="block text-xs">{label}<input aria-label={`${label}: ${p.name}`} className={input} type="number" min={min} max={max} step={key==='visits_per_week'?1:'any'} value={trip[key] ?? ''} onChange={e=>update({[key]:number(e.target.value)})}/></label>)}<p className="text-xs">Мягкий предел даёт нулевую полезность, но не исключает вариант. Исключение происходит только при нарушении обязательного максимума.</p></fieldset>;})}
    <label className="flex gap-2 text-sm"><input aria-label="Подтвердить вес поездок" type="checkbox" checked={settings.frequency_weighting_confirmed} onChange={e=>change({frequency_weighting_confirmed:e.target.checked})}/>Подтверждаю: вес поездки равен важности × числу поездок в неделю.</label>
    {draft.housing_goal!=='buy' && <p role="status" className="text-sm">Аренда и сравнение покупки с арендой пока не поддерживают полный Match. Данные покупки не заменят данные аренды.</p>}
  </section>;
}
