"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Compass, Layers3, MapPin, Sparkles } from "lucide-react";
import { Brand, DemoBadge, DistrictInsightCard, EmptyState, ScoreRing, Skeleton } from "@/components/concept-ui";
import { demoDistrict, demoLayers, type LayerId } from "@/lib/demo-data";
import { useOnboarding } from "@/lib/onboarding-store";

const DistrictMap = dynamic(() => import("@/components/district-map"), { ssr: false, loading: () => <Skeleton className="h-[580px] w-full bg-[#dbeae5]" /> });
export default function DistrictPage() {
  const [active, setActive] = useState<LayerId[]>(["housing", "schools", "parks", "transport", "development", "life"]);
  const points = useOnboarding((state) => state.draft.life_points);
  function toggle(id: LayerId) { setActive((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  return <main className="page-shell"><header className="content-shell flex h-20 items-center justify-between"><Brand /><div className="flex items-center gap-3"><DemoBadge /><Link href="/results" className="hidden text-xs font-semibold text-[#abc6c7] sm:inline">К результату</Link></div></header>
    <section className="border-t border-white/10 bg-[#092030]"><div className="content-shell py-12 sm:py-16"><Link href="/results" className="inline-flex items-center gap-2 text-xs font-semibold text-[#91cfc1]"><ArrowLeft size={15} /> К результату</Link><p className="eyebrow mt-8">Интерактивная карта · Красноярск</p><div className="mt-4 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-[clamp(2.8rem,6vw,5.8rem)] font-semibold leading-none tracking-[-.07em]">Увидеть место <span className="gradient-text">целиком.</span></h1><p className="mt-5 max-w-2xl text-sm leading-relaxed text-[#a8c3c4]">Демо-объекты, планы и ваши точки жизни в одном пространстве. Пунктирный контур показывает только область примера, не официальную границу района.</p></div><div className="flex items-center gap-3 rounded-[22px] border border-white/10 bg-white/[.06] p-3 pr-6"><ScoreRing value={demoDistrict.score} size="small" /><div><span className="text-xs text-[#9bc4bf]">Демо-совпадение</span><p className="text-xl font-semibold">{demoDistrict.name}</p></div></div></div></div></section>
    <section className="bg-[#f0f7f3] py-8 text-[#14333e] sm:py-12"><div className="content-shell grid gap-6 lg:grid-cols-[300px_1fr] xl:grid-cols-[340px_1fr]"><aside className="space-y-5"><div className="rounded-[26px] border border-[#dbe8e4] bg-white p-6"><div className="flex items-center gap-2"><Layers3 size={19} className="text-[#18a186]" /><h2 className="text-xl font-semibold tracking-[-.04em]">Слои карты</h2></div><p className="mt-2 text-xs leading-relaxed text-[#779295]">Включайте то, что важно для вашего дня.</p><div className="mt-6 grid grid-cols-2 gap-2 lg:grid-cols-1">{demoLayers.map((layer) => <button key={layer.id} type="button" onClick={() => toggle(layer.id)} aria-pressed={active.includes(layer.id)} className={`flex min-h-11 items-center justify-between gap-2 rounded-xl border px-3 text-left text-sm transition ${active.includes(layer.id) ? "border-[#b7dfd2] bg-[#e8f8f0] text-[#20575a]" : "border-[#e1e9e5] bg-white text-[#859899]"}`}><span className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: layer.color }} />{layer.label}</span><span className={`h-4 w-7 rounded-full p-0.5 ${active.includes(layer.id) ? "bg-[#23ae91]" : "bg-[#d1dcd8]"}`}><span className={`block h-3 w-3 rounded-full bg-white transition-transform ${active.includes(layer.id) ? "translate-x-3" : ""}`} /></span></button>)}</div><p className="mt-5 text-[11px] leading-relaxed text-[#859b9b]">Все цветные объекты — иллюстративные. Базовая подложка: OpenStreetMap.</p></div>{points.length === 0 ? <EmptyState title="Ваших точек пока нет" body="Добавьте важные места в анкете, чтобы увидеть их на карте." /> : <div className="rounded-[24px] border border-[#dbe8e4] bg-white p-5"><p className="text-sm font-semibold">Ваши точки жизни</p><ul className="mt-3 space-y-2">{points.map((point) => <li key={point.localId} className="flex items-center gap-2 text-xs text-[#5f8184]"><MapPin size={14} className="text-[#187dda]" />{point.name}</li>)}</ul></div>}<Link href="/onboarding" className="inline-flex items-center gap-2 text-sm font-semibold text-[#138d7b]">Добавить точки <ArrowRight size={16} /></Link></aside><div><DistrictMap active={active} points={points} /><div className="mt-4 flex flex-wrap items-center gap-3 text-xs text-[#6c898c]"><span className="inline-flex items-center gap-2"><span className="h-3 w-5 rounded border-2 border-dashed border-[#069b82]" /> Область примера</span><span className="inline-flex items-center gap-2"><span className="h-3 w-3 rounded-full bg-[#147dea]" /> Ваша точка</span><span className="inline-flex items-center gap-2"><Sparkles size={13} /> Демо-объекты</span></div></div></div></section>
    <section className="content-shell grid gap-5 py-16 lg:grid-cols-[1fr_400px] lg:items-center"><div><p className="eyebrow">Контекст выбора</p><h2 className="section-title mt-4">Район — это <span className="gradient-text">больше, чем точка.</span></h2><p className="mt-5 max-w-xl text-sm leading-relaxed text-[#a3bfc0]">Карта помогает увидеть связь маршрутов, инфраструктуры и будущих изменений. В этом концепте точки и показатели служат примером интерфейса.</p><Link href="/results" className="secondary-button mt-8"><Compass size={16} /> Вернуться к обзору</Link></div><DistrictInsightCard compact /></section>
    <footer className="border-t border-white/10 py-8"><div className="content-shell text-xs text-[#74969a]">МЕСТО · концепт MVP · демонстрационные объекты не отражают фактическую инфраструктуру</div></footer>
  </main>;
}
